name: GriefPrevention
main: me.ryanhamshire.GriefPrevention.GriefPrevention
softdepend: [Vault, Multiverse-Core, My_Worlds, MystCraft, Transporter, TheUnderground, WorldGuard, WorldEdit, RoyalCommands, MultiWorld, Denizen]
dev-url: https://dev.bukkit.org/projects/grief-prevention
loadbefore: [TheUnderground]
version: '${git.commit.id.describe}'
api-version: '1.17'
commands:
    manageland:
      usage: '§b/manageland§f: §7Manage your claim through a fancy menu.'
      aliases: [manageclaim]
      description: Manage your claim(s) through a menu.
    abandonclaim:
      description: Deletes a claim.
      usage: '§b/unclaim§f: §7Abandon the claim you are currently in.'
      aliases: [unclaim, declaim, removeclaim, disclaim]
      permission: griefprevention.claims
    abandontoplevelclaim:
      description: Deletes a claim and all its subdivisions.
      usage: '§b/abandontoplevelclaim§f: §7Abandon the top level claim of your current location.'
      permission: griefprevention.claims
    abandonallclaims:
      description: Deletes ALL your claims.
      usage: /abandonallclaims
      permission: griefprevention.claims
    trust:
      description: Grants a player full access to your claim(s).
      usage: '§b/trust §f<player>: §7Grant a player permission to build on your current claim.'
      aliases: tr
      permission: griefprevention.claims
    untrust:
      description: Revokes a player's access to your claim(s).
      usage: '§b/untrust §f<player>: §7Completely revoke someone''s access to your claim.'
      aliases: ut
      permission: griefprevention.claims
    containertrust:
      description: Grants a player access to your claim's containers, crops, animals, bed, buttons, and levers.
      usage: '§b/containertrust §f<player>: §7Grant a player permission to access your containers, crops, animals, beds, and buttons/levels on your current claim.'
      aliases: ct
      permission: griefprevention.claims
    accesstrust:
      description: Grants a player entry to your claim(s) and use of your bed, buttons, and levers.
      usage: '§b/accesstrust §f<player>: §7Grant a player permission to use your beds and buttons/levers on your current claim.'
      aliases: at
      permission: griefprevention.claims
    permissiontrust:
      description: Grants a player permission to grant his level of permission to others.
      usage: '§b/permissiontrust §f<player>: §7Permit a player to share his permission level with others.'
      aliases: pt
      permission: griefprevention.claims
    subdivideclaims:
      description: Switches the shovel tool to subdivision mode, used to subdivide your claims.
      usage: '§b/subdivideclaims§f: §7Switches the shovel tool to subdivision mode, used to subdivide your claims.'
      aliases: [sc, subdivideclaim]
      permission: griefprevention.claims
    restrictsubclaim:
      description: Restricts a subclaim, so that it inherits no permissions from the parent claim
      usage: '§b/restrictsubclaim§f: §7Restrict a subclaim, so that it inherits no permissions from the parent claim.'
      aliases: rsc
      permission: griefprevention.claims
    adjustbonusclaimblocks:
      description: Adds or subtracts bonus claim blocks for a player.
      usage: '§b/adjustbonusclaimblocks §f<player> <amount>: §7Add/remove bonus claim blocks to/from a player.'
      permission: griefprevention.adjustclaimblocks
      aliases: acb
    adjustbonusclaimblocksall:
      description: Adds or subtracts bonus claim blocks for all online players.
      usage: '§b/adjustbonusclaimblocksall §f<amount>: §7Add/remove bonus claim blocks to/from all online players.'
      permission: griefprevention.adjustclaimblocks
      aliases: acball
    setaccruedclaimblocks:
      description: Updates a player's accrued claim block total.
      usage: '§b/setaccruedclaimblocks §f<player> <amount>: §7Update a player''s accrued claim block total.'
      permission: griefprevention.adjustclaimblocks
      aliases: scb
    deleteclaim:
      description: Deletes the claim you're standing in, even if it's not your claim.
      usage: '§b/deleteclaim§f: §7Delete the claim you''re standing in'
      permission: griefprevention.deleteclaims
    deleteallclaims:
      description: Deletes all of another player's claims.
      usage: '§b/deleteclaims §f<player>: §7Delete all claims of a player.'
      permission: griefprevention.deleteclaims
    deleteclaimsinworld:
      description: Deletes all the claims in a world.  Only usable at the server console.
      usage: '§b/deleteclaimsinworld §f<world>: §7Delete all the claims in a world.'
      aliases: [deleteallclaimsinworld, clearclaimsinworld, clearallclaimsinworld]
      permission: griefprevention.deleteclaimsinworld
    deleteuserclaimsinworld:
      description: Deletes all the non-admin claims in a world.  Only usable at the server console.
      usage: '§b/deleteuserclaimsinworld §f<world>: §7Delete all non-admin claims in a world.'
      aliases: [deletealluserclaimsinworld, clearuserclaimsinworld, clearalluserclaimsinworld]
      permission: griefprevention.deleteclaimsinworld
    adminclaims:
      description: Switches the shovel tool to administrative claims mode.
      usage: '§b/adminclaims§f: §7Switches the shovel tool to administrative claims mode.'
      permission: griefprevention.adminclaims
      aliases: ac
    restorenature:
      description: Switches the shovel tool to restoration mode.
      usage: '§b/restorenature§f: §7Switches the shovel tool to restoration mode.'
      permission: griefprevention.restorenature
      aliases: rn
    restorenatureaggressive:
      description: Switches the shovel tool to aggressive restoration mode.
      usage: '§b/restorenatureaggressive§f: §7Switches the shovel tool to aggressive restoration mode.'
      permission: griefprevention.restorenatureaggressive
      aliases: rna
    restorenaturefill:
      description: Switches the shovel tool to fill mode.
      usage: '§b/restorenaturefill §f<radius>: §7Switches the shovel tool to fill mode.'
      permission: griefprevention.restorenatureaggressive
      aliases: rnf
    basicclaims:
      description: Switches the shovel tool back to basic claims mode.
      usage: '§b/basicclaims§f: §7Switches the shovel tool back to basic claims mode.'
      aliases: bc
      permission: griefprevention.claims
    extendclaim:
      description: Resizes the land claim you're standing in by pushing or pulling its boundary in the direction you're facing.
      usage: '§b/extendclaim §f<number_of_blocks>: §7Expand the claim you''re standing in by pushing/pulling its boundary in the direction you are facing.'
      aliases: [expandclaim, resizeclaim]
      permission: griefprevention.claims
    claim:
      description: Creates a land claim centered at your current location.
      usage: '§b/claim §f[radius]: §7Claim a piece of land around your location.'
      aliases: [createclaim, makeclaim, newclaim]
      permission: griefprevention.claims
    buyclaimblocks:
      description: Purchases additional claim blocks with server money.
      usage: '§b/buyclaimblocks §f<number_of_blocks>: §7Purchase additional claim blocks.'
      aliases: buyclaim
      permission: griefprevention.buysellclaimblocks
    sellclaimblocks:
      description: Sells your claim blocks for server money.
      usage: '§b/sellclaimblocks §f<number_of_blocks>: §7Sell your claim blocks.'
      aliases: sellclaim
      permission: griefprevention.buysellclaimblocks
    trapped:
      description: Ejects you to nearby unclaimed land. Has a substantial cooldown period.
      usage: '§b/trapped§f: §7Eject yourself to nearby unclaimed land.'
      permission: griefprevention.trapped
    trustlist:
      description: Lists permissions for the claim you're standing in.
      usage: '§b/trustlist§f: §7Get a list of trusted players for the claim you''re standing in.'
      permission: griefprevention.claims
    siege:
      description: Initiates a siege versus another player.
      usage: '§b/siege §f<player>: §7Initiates siege against another player.'
      permission: griefprevention.siege
    ignoreclaims:
      description: Toggles ignore claims mode.
      usage: '§b/ignoreclaims§f: §7Toggles ignore claims mode.'
      permission: griefprevention.ignoreclaims
      aliases: ic
    deletealladminclaims:
      description: Deletes all administrative claims.
      usage: '§b/deletealladminclaims§f: §7Delete all administrative claims.'
      permission: griefprevention.adminclaims
    adminclaimslist:
      description: Lists all administrative claims.
      usage: '§b/adminclaimslist§f: §7Get a list of all administrative claims.'
      permission: griefprevention.adminclaims
    transferclaim:
      description: Converts an administrative claim to a private claim.
      usage: '§b/transferclaim §f<player>: §7Convert an administrative claim to a private claim.'
      aliases: giveclaim
      permission: griefprevention.transferclaim
    unlockdrops:
      description: Allows other players to pick up the items you dropped when you died.
      usage: '§b/unlockdrops§f: §7Allow other players to pick up the items that you drop when you die.'
      permission: griefprevention.unlockdrops
    claimslist:
      description: Lists information about a player's claim blocks and claims.
      usage: '§b/claimslist §f[player]: §7Get a list of a player''s claims and blocks information.'
      aliases: [claimlist, listclaims]
      permission: griefprevention.claims
    claimexplosions:
      description: Toggles whether explosives may be used in a specific land claim.
      usage: '§b/claimexplosions§f: Toggle whether explosives may be used in a land claim.'
      permission: griefprevention.claims
      aliases: claimexplosion
    softmute:
      description: Toggles whether a player's messages will only reach other soft-muted players.
      usage: '§b/softmute §f<player>: §7Toggle whether a player''s messages will only reach other soft-muted players.'
      permission: griefprevention.softmute
    gpreload:
      description: Reloads Grief Prevention's configuration settings.  Does NOT totally reload the entire plugin.
      usage: '§b/gpreload§f: §7Reload the plugin.'
      permission: griefprevention.reload
    givepet:
      description: Allows a player to give away a pet he or she tamed.
      usage: '§b/givepet §f<player>: §7Give away a pet you tamed.'
      permission: griefprevention.givepet
    gpblockinfo:
      description: Allows an administrator to get technical information about blocks in the world and items in hand.
      usage: '§b/gpblockinfo§f: §7Get technical information about blocks in the world.'
      permission: griefprevention.gpblockinfo
    ignoreplayer:
      description: Ignores another player's chat messages.
      usage: '§b/ignoreplayer §f<player>: §7Ignore a player''s chat messages.'
      aliases: [ignore]
      permission: griefprevention.ignore
    unignoreplayer:
      description: Unignores another player's chat messages.
      usage: '§b/unignore §f<player>: §7Unignore a player''s chat messages.'
      aliases: [unignore]
      permission: griefprevention.ignore
    ignoredplayerlist:
      description: Lists the players you're ignoring in chat.
      usage: '§b/ignoredplayerlist§f: §7Get a list of players you ignored.'
      aliases: [ignores, ignored, ignorelist, ignoredlist, listignores, listignored, ignoring]
      permission: griefprevention.ignore
    separate:
      description: Forces two players to ignore each other in chat.
      usage: '§b/separate §f<player1> <player2>: §7Force two players to ignore each other in chat.'
      permission: griefprevention.separate
    unseparate:
      description: Reverses /separate.
      usage: '§b/unseparate§f: §7Force two players to unignore each other in chat.'
      permission: griefprevention.separate
    claimbook:
      description: Gives a player a manual about claiming land.
      usage: '§b/claimbook §f<player>: §7Give a player a claim manual.'
      permission: griefprevention.claimbook
permissions:
    griefprevention.createclaims:
        description: Grants permission to create claims.
        default: true
    griefprevention.admin.*:
        description: Grants all administrative functionality.
        children:
            griefprevention.restorenature: true
            griefprevention.restorenatureaggressive: true
            griefprevention.ignoreclaims: true
            griefprevention.adminclaims: true
            griefprevention.adjustclaimblocks: true
            griefprevention.deleteclaims: true
            griefprevention.spam: true
            griefprevention.lava: true
            griefprevention.eavesdrop: true
            griefprevention.deathblow: true
            griefprevention.softmute: true
            griefprevention.reload: true
            griefprevention.visualizenearbyclaims: true
            griefprevention.overrideclaimcountlimit: true
            griefprevention.transferclaim: true
            griefprevention.claimslistother: true
            griefprevention.siegeimmune: true
            griefprevention.separate: true
            griefprevention.eavesdropsigns: true
            griefprevention.claimbook: true
            griefprevention.notignorable: true
            griefprevention.seeinactivity: true
            griefprevention.eavesdropimmune: true
            griefprevention.deleteclaimsinworld: true
            griefprevention.siegeteleport: true
            griefprevention.unlockothersdrops: true
            griefprevention.seeclaimsize: true
    griefprevention.siegeimmune:
        description: Makes a player immune to /Siege.
        default: op
    griefprevention.givepet:
        description: Grants permission to use /GivePet.
        default: true
    griefprevention.siege:
        description: Grants permission to use /Siege.
        default: true
    griefprevention.unlockdrops:
        description: Grants permission to use /UnlockDrops.
        default: true
    griefprevention.unlockothersdrops:
        description: Grants permission to use /UnlockDrops for other players.
        default: op
    griefprevention.trapped:
        description: Grants permission to use /Trapped.
        default: true
    griefprevention.claimslistother:
        description: Grants permission to use /ClaimsList to get another player's information.
        default: op
    griefprevention.restorenature:
        description: Grants permission to use /RestoreNature.
        default: op
    griefprevention.transferclaim:
        description: Grants permission to use /TransferClaim.
        default: op
    griefprevention.ignoreclaims:
        description: Grants permission to use /IgnoreClaims.
        default: op
    griefprevention.adminclaims:
        description: Grants permission to create administrative claims.
        default: op
    griefprevention.deleteclaims:
        description: Grants permission to delete other players' claims.
        default: op
    griefprevention.deleteclaimsinworld:
        description: Not used.  DeleteClaimsInWorld must be executed at the server console.
        default: op
    griefprevention.adjustclaimblocks:
        description: Grants permission to add or remove bonus blocks from a player's account.
        default: op
    griefprevention.spam:
        description: Grants permission to log in, send messages, and send commands rapidly.
        default: op
    griefprevention.lava:
        description: Grants permission to place lava near the surface and outside of claims.
        default: op
    griefprevention.eavesdrop:
        description: Allows a player to see whispered chat messages (/tell) and softmuted messages.
        default: op
    griefprevention.eavesdropsigns:
        description: Allows a player to see sign placements as chat messages.
        default: op
    griefprevention.restorenatureaggressive:
        description: Grants access to /RestoreNatureAggressive and /RestoreNatureFill.
        default: op
    griefprevention.deathblow:
        description: Grants access to /DeathBlow.
        default: op
    griefprevention.reload:
        description: Grants access to /gpreload.
        default: op
    griefprevention.softmute:
        description: Grants access to /SoftMute.
        default: op
    griefprevention.claims:
        description: Grants access to claim-related slash commands.
        default: true
    griefprevention.buysellclaimblocks:
        description: Grants access to claim block buy/sell commands.
        default: true
    griefprevention.visualizenearbyclaims:
        description: Allows a player to see all nearby claims at once.
        default: op
    griefprevention.seeclaimsize:
        description: Allows a player to see claim size for other players claims when right clicking with investigation tool
        default: op
    griefprevention.gpblockinfo:
        description: Grants access to /GPBlockInfo.
        default: op
    griefprevention.overrideclaimcountlimit:
        description: Allows players to create more claims than the limit specified by the config.
        default: op
    griefprevention.separate:
        description: Grants access to /Separate and /UnSeparate.
        default: op
    griefprevention.ignore:
        description: Grants access to /Ignore, /Unignore, and /IgnoreList
        default: true
    griefprevention.claimbook:
        description: Grants access to /ClaimBook.
        default: op
    griefprevention.notignorable:
        description: Players with this permission can't be ignored.
        default: op
    griefprevention.seeinactivity:
        description: Players with this permission can see how long a claim owner has been offline.
        default: op
    griefprevention.eavesdropimmune:
        description: Players with this permission can't have their private messages eavesdropped.
        default: op
    griefprevention.fasteraccrual:
        description: Players with this permission accrue claim blocks at the faster rate specified in the config file.
        default: false
    griefprevention.fastestaccrual:
        description: Players with this permission accrue claim blocks at the fastest rate specified in the config file.
        default: false
    griefprevention.moreaccrued:
        description: Players with this permission can accrue more claim blocks (limit specified in the config file).
        default: false
    griefprevention.mostaccrued:
        description: Players with this permission can accrue more claim blocks (limit specified in the config file).
        default: false
    griefprevention.siegeteleport:
        description: Players with this permission can teleport into and out of besieged areas.
        default: op
